util.h: endian.h is available on musl on linux
just checking for glibc alone is not enough since
it excludes musl, therefore check for platform
being linux as well

Fixes build issues

include/libisns/util.h:114:12: fatal error: sys/endian.h: No such file or directory
 #  include <sys/endian.h>
            ^~~~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>