isnsadm: Fix unparse command line options "-V" and "-r"
Following error would reported:

root@fedora:# isnsadm -V
isnsadm: invalid option -- 'V'
Error: Unknown option

root@fedora:# isnsadm -r
isnsadm: invalid option -- 'r'
Error: Unknown option

This is because we did not add "V" and "r" to parameter
when calling getopt_long()

Signed-off-by: Wenchao Hao <haowenchao@huawei.com>